package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type commandHelp struct {
	Summary string
	Args    []argHelp
}

type argHelp struct {
	Name        string
	Description string
}

func main() {
	inputPath := flag.String("input", defaultInputPath(), "path to command-summary.md")
	outputPath := flag.String("output", filepath.Join("internal", "cmdhelp", "data.go"), "path to generated Go file")
	flag.Parse()

	input, err := os.Open(*inputPath)
	if err != nil {
		exitf("open input: %v", err)
	}
	defer input.Close()

	commands, err := parseCommandSummary(input)
	if err != nil {
		exitf("parse input: %v", err)
	}

	rendered, err := renderDataFile(commands)
	if err != nil {
		exitf("render output: %v", err)
	}

	if err := os.MkdirAll(filepath.Dir(*outputPath), 0o755); err != nil {
		exitf("create output dir: %v", err)
	}
	if err := os.WriteFile(*outputPath, rendered, 0o644); err != nil {
		exitf("write output: %v", err)
	}
}

func defaultInputPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return filepath.Join("~", "git_tree", "tmux", "command-summary.md")
	}
	return filepath.Join(home, "git_tree", "tmux", "command-summary.md")
}

func parseCommandSummary(r io.Reader) (map[string]commandHelp, error) {
	scanner := bufio.NewScanner(r)
	commands := make(map[string]commandHelp)

	var currentName string
	var current commandHelp
	inArgs := false

	flush := func() {
		if currentName == "" {
			return
		}
		commands[currentName] = current
	}

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}

		switch {
		case strings.HasPrefix(line, "command: "):
			flush()
			currentName = strings.TrimSpace(strings.TrimPrefix(line, "command: "))
			current = commandHelp{}
			inArgs = false
		case strings.HasPrefix(line, "command-summary: "):
			current.Summary = strings.TrimSpace(strings.TrimPrefix(line, "command-summary: "))
		case line == "command-args:":
			inArgs = true
		case inArgs:
			name, description, _ := strings.Cut(line, " ")
			current.Args = append(current.Args, argHelp{
				Name:        strings.TrimSpace(name),
				Description: strings.TrimSpace(description),
			})
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	flush()

	return commands, nil
}

func renderDataFile(commands map[string]commandHelp) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/gen_command_help; DO NOT EDIT.\n")
	buf.WriteString("package cmdhelp\n\n")
	buf.WriteString("type CommandHelp struct {\n\tSummary string\n\tArgs    []ArgHelp\n}\n\n")
	buf.WriteString("type ArgHelp struct {\n\tName        string\n\tDescription string\n}\n\n")
	buf.WriteString("var Commands = map[string]CommandHelp{\n")

	keys := make([]string, 0, len(commands))
	for key := range commands {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	for _, key := range keys {
		cmd := commands[key]
		fmt.Fprintf(&buf, "\t%q: {\n", key)
		fmt.Fprintf(&buf, "\t\tSummary: %q,\n", cmd.Summary)
		buf.WriteString("\t\tArgs: []ArgHelp{\n")
		for _, arg := range cmd.Args {
			fmt.Fprintf(&buf, "\t\t\t{Name: %q, Description: %q},\n", arg.Name, arg.Description)
		}
		buf.WriteString("\t\t},\n")
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	return format.Source(buf.Bytes())
}

func exitf(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
